<a href="https://colab.research.google.com/github/gabriellopes-eng/Data-Science-Notes/blob/main/21_02_26_01_2_CE_CDSP_2026_pra%CC%81tica_aula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Python para Ciência de Dados em Saúde Pública**



Prof. Dr. Maicon Herverton Lino Ferreira da Silva Barros (UPE)

Prof. Dr. Walter Massa Ramalho (UnB)

Prof. Ph.D. Mauro Niskier Sanchez (UnB)


---


**Módulo:** 21/02/2026

**Prática:** NumPy, Array, Matrizes, Pandas, Redundância, duplicação, transformação.





# NumPy, Array, Matrizes e Pandas



## **NumPy**

Como estamos utilizando o Colab, o mesmo já possui algumas bibliotecas básicas pré-instaladas. Portanto, precisamos apenas importá-la usando a palavra-chave ***import***.


Exemplo:

In [ ]:
import numpy

## **Array**

Como criar um ***array*** com numpy?


Exemplo:

In [ ]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5]) #array unidimensional de 5 posições
print(arr)

[1 2 3 4 5]


Em python nós rotulamos as bibliotecas geralmente com dois caracteres para facilitar a compreensão "**chave**" do código e não ficar estendendo nomes durante o código.

Para fazer isso usamos a palavra-chave ***as*** logo após a importação da biblioteca desejada.

Exemplo:


In [ ]:
import numpy as np #perceba que nomeamos a biblioteca numpy como np
arr = np.array([1, 2, 3, 4, 5]) #agora np possui todas as funções que numpy disponibiliza (métodos)
print(arr)

[1 2 3 4 5]


Lembrete: como o python é uma linguagem que está em constante evolução, muitas funções da biblioteca são implementada ao longo dos anos. Portanto, caso encontre alguma função que queira utilizar nos seus códigos é necessário entender se a versão da biblioteca que está utilizando possui aquela função.

Para verificar a versão utilizamos uma variável constante denominada de __version__

Exemplo:

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


## **Matrizes**

In [ ]:
#Exemplo 0 dimensões:
import numpy as np
arr = np.array(50)
print(arr)

50


In [ ]:
#Exemplo 1 dimensões:
import numpy as np
arr = np.array([1,2,3,10])
print(arr)

[ 1  2  3 10]


In [ ]:
#Exemplo 2 dimensões:
import numpy as np
arr = np.array([[1, 2, 3], [1, 2, 3]])
print(arr)
print("Número de dimensões: ",arr.ndim)

[[1 2 3]
 [1 2 3]]
Número de dimensões:  2


## **Índices**

Para acessar os elementos de um array já sabemos que usamos o índice (coluna) de 0 até o número de elementos constantes naquele array - 1. Ou seja, se tenho 10 elementos posso resgatar estes elementos consultando de 0 a 9 (10 registros).

Exemplo:


In [ ]:
import numpy as np
arr = np.array([10, 20, 33, 40])
#               0   1   2   3
print(arr[2] + arr[3])

73


Para elementos de uma matriz usamos o mesmo princípio, só que agora temos que indicar a linha:

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('O segundo elemento da primeira linha é: ', arr[0, 1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
O segundo elemento da primeira linha é:  2


## **Shape**

Temos um atributo comum a todos os objetos que criamos com NumPy chamado de shape (forma). Com ele podemos determinar quantas linhas e colunas possui uma matriz bidimensional no python;

Exemplo:


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


## **Pandas**

Como estamos utilizando o Colab, o mesmo já possui algumas bibliotecas básicas pré-instaladas. Portanto, precisamos apenas importá-la usando a palavra-chave import.


In [ ]:
import pandas as pd

Como criar o nosso primeiro data set com pandas?

Exemplo:

In [ ]:
import pandas as pd
meu_data_set = {
  'paciente': ["João", "José", "Maria"],
  'idade': [33, 70, 20]
}
meu_objeto = pd.DataFrame(meu_data_set)
print(meu_objeto)

  paciente  idade
0     João     33
1     José     70
2    Maria     20


In [ ]:
import pandas as pd
a = [1, 7, 2]
meu_objeto = pd.Series(a)
print(meu_objeto)

0    1
1    7
2    2
dtype: int64


### **Series**

Uma ***series*** em Pandas é como uma coluna em uma matriz ou tabela.

Exemplo:

In [ ]:
import pandas as pd
a = [1, 7, 2]
meu_objeto = pd.Series(a)
print(meu_objeto)

0    1
1    7
2    2
dtype: int64


Podemos acessar através do índice como fizemos com array/matrizes ou podemos rotular as nossas ***series***.

Exemplo:


In [ ]:
import pandas as pd
a = ["joão", "M", "Sul"]
meu_objeto = pd.Series(a, index = ["nome", "sexo", "região"])
print(meu_objeto)
print("Valor do elemento com índice rotulado em [x]:",meu_objeto["região"])

nome      joão
sexo         M
região     Sul
dtype: object
Valor do elemento com índice rotulado em [x]: Sul


Podemos criar "filtros" usando uma series que foi criada com chave/valor. Isso é útil quando queremos filtrar apenas alguns elementos:

Exemplo:


In [ ]:
import pandas as pd
glicose = {"dia1": 98, "dia2": 150, "dia3": 2}
meu_objeto = pd.Series(glicose,index=["dia1", "dia2"])
print(meu_objeto)

dia1     98
dia2    150
dtype: int64


### **DataFrame**

Chamamos de ***DataFrames*** em Pandas os *data sets*, que geralmente são tabelas multidimensionais:

***Series*** são uma coluna, ***DataFrame*** é a tabela inteira.

Exemplo:


In [ ]:
import pandas as pd
dados = {
  "glicose": [98, 250, 100],
  "idade": [20, 80, 45]
}
df = pd.DataFrame(dados)
print(type(df))
print(df)

<class 'pandas.core.frame.DataFrame'>
   glicose  idade
0       98     20
1      250     80
2      100     45


Para localizar uma linha em um DataFrame o pandas conta com o atributo ***loc***, e podemos especificar uma ou mais linhas:

Exemplo:


In [ ]:
#referenciando o índice da linha:
print(df.loc[0])
print(type(df.loc[0])) #perceba que o retorno é uma Series do Pandas

glicose    98
idade      20
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>



Exemplo retornando a linha 0 e 1

In [ ]:
#usando uma lista de índices:
print(df.loc[[0, 1]])
print(type(df.loc[[0, 1]])) #perceba que o retorno (como é mais de uma linha) é DataFrame

   glicose  idade
0       98     20
1      250     80
<class 'pandas.core.frame.DataFrame'>


### **DataFrame - Upload**

In [ ]:
from google.colab import files
uploaded = files.upload()
for fn in uploaded.keys():
 print('Arquivo: "{nome}" tamanho: {tamanho} bytes'.format(nome=fn, tamanho=len(uploaded[fn])))

Saving aula_02_iris.csv to aula_02_iris.csv
Arquivo: "aula_02_iris.csv" tamanho: 4601 bytes


In [ ]:
import pandas as pd
df = pd.read_csv('aula_02_iris.csv') #o arquivo só existirá se você tiver realizado o upload na célula anterior
df

,sepal_l_cm,sepal_w_cm,petal_l_cm,petal_w_cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica


Outra alternativa é montar uma pasta local no **Google Drive** e utilizar um arquivo que você já fez upload para nuvem da google.

Exemplo:


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
arquivo = '/content/drive/MyDrive/CE_Extensao_2026.1_CDSP/datasets/aula_02_iris.csv'
df = pd.read_csv(arquivo) #você só terá acesso ao arquivo se autorizar o Colab a acessar o seu Google drive rodando o comando da célular anterior
print(df)

     sepal_l_cm  sepal_w_cm  petal_l_cm  petal_w_cm           class
0           5.1         3.5         1.4         0.2     Iris-setosa
1           4.9         3.0         1.4         0.2     Iris-setosa
2           4.7         3.2         1.3         0.2     Iris-setosa
3           4.6         3.1         1.5         0.2     Iris-setosa
4           5.0         3.6         1.4         0.2     Iris-setosa
..          ...         ...         ...         ...             ...
145         6.7         3.0         5.2         2.3  Iris-virginica
146         6.3         2.5         5.0         1.9  Iris-virginica
147         6.5         3.0         5.2         2.0  Iris-virginica
148         6.2         3.4         5.4         2.3  Iris-virginica
149         5.9         3.0         5.1         1.8  Iris-virginica

[150 rows x 5 columns]


Um dos métodos mais comuns para visualização rápida de um DataFrame é o ***head()***

Ele retorna cabeçalhos e um número específico de linhas.

Exemplo:

In [ ]:
print(df.head(10))

   sepal_l_cm  sepal_w_cm  petal_l_cm  petal_w_cm        class
0         5.1         3.5         1.4         0.2  Iris-setosa
1         4.9         3.0         1.4         0.2  Iris-setosa
2         4.7         3.2         1.3         0.2  Iris-setosa
3         4.6         3.1         1.5         0.2  Iris-setosa
4         5.0         3.6         1.4         0.2  Iris-setosa
5         5.4         3.9         1.7         0.4  Iris-setosa
6         4.6         3.4         1.4         0.3  Iris-setosa
7         5.0         3.4         1.5         0.2  Iris-setosa
8         4.4         2.9         1.4         0.2  Iris-setosa
9         4.9         3.1         1.5         0.1  Iris-setosa


In [ ]:
print(df.head()) #por padrão o método imprime as 5 primeiras linhas do DataFrame

   sepal_l_cm  sepal_w_cm  petal_l_cm  petal_w_cm        class
0         5.1         3.5         1.4         0.2  Iris-setosa
1         4.9         3.0         1.4         0.2  Iris-setosa
2         4.7         3.2         1.3         0.2  Iris-setosa
3         4.6         3.1         1.5         0.2  Iris-setosa
4         5.0         3.6         1.4         0.2  Iris-setosa


In [ ]:
df.head() #por padrão o método imprime as 5 primeiras linhas do DataFrame

,sepal_l_cm,sepal_w_cm,petal_l_cm,petal_w_cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


Para visualizar as últimas linhas usamos o método ***tail()***

Exemplo:


In [ ]:
print(df.tail()) #por padrão o método imprime as 5 últimas linhas do DataFrame

     sepal_l_cm  sepal_w_cm  petal_l_cm  petal_w_cm           class
145         6.7         3.0         5.2         2.3  Iris-virginica
146         6.3         2.5         5.0         1.9  Iris-virginica
147         6.5         3.0         5.2         2.0  Iris-virginica
148         6.2         3.4         5.4         2.3  Iris-virginica
149         5.9         3.0         5.1         1.8  Iris-virginica


Para uma amostra aleatória do DataFrame podemos usar o método sample()

Exemplo:


In [ ]:
print(df.sample(25)) #execute várias vezes e perceba que os índices dos registros mudam (pois se tratam de outros registros aleatórios a cada execução)

     sepal_l_cm  sepal_w_cm  petal_l_cm  petal_w_cm            class
61          5.9         3.0         4.2         1.5  Iris-versicolor
74          6.4         2.9         4.3         1.3  Iris-versicolor
88          5.6         3.0         4.1         1.3  Iris-versicolor
28          5.2         3.4         1.4         0.2      Iris-setosa
13          4.3         3.0         1.1         0.1      Iris-setosa
35          5.0         3.2         1.2         0.2      Iris-setosa
97          6.2         2.9         4.3         1.3  Iris-versicolor
111         6.4         2.7         5.3         1.9   Iris-virginica
5           5.4         3.9         1.7         0.4      Iris-setosa
140         6.7         3.1         5.6         2.4   Iris-virginica
41          4.5         2.3         1.3         0.3      Iris-setosa
8           4.4         2.9         1.4         0.2      Iris-setosa
40          5.0         3.5         1.3         0.3      Iris-setosa
71          6.1         2.8       

Para obtermos informações sobre os dados que estão em um DataFrame podemos usar  o método ***info() ***

Exemplo:


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   sepal_l_cm  150 non-null    float64
 1   sepal_w_cm  150 non-null    float64
 2   petal_l_cm  150 non-null    float64
 3   petal_w_cm  150 non-null    float64
 4   class       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [ ]:
df.columns

Index(['sepal_l_cm', 'sepal_w_cm', 'petal_l_cm', 'petal_w_cm', 'class'], dtype='object')

Podemos importar o DataFrame apenas com colunas específicas

Exemplo:


In [ ]:
df = pd.read_csv(arquivo, sep=',', usecols=['sepal_l_cm','class'])
df.head()

,sepal_l_cm,class
0,5.1,Iris-setosa
1,4.9,Iris-setosa
2,4.7,Iris-setosa
3,4.6,Iris-setosa
4,5.0,Iris-setosa


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   sepal_l_cm  150 non-null    float64
 1   class       150 non-null    object 
dtypes: float64(1), object(1)
memory usage: 2.5+ KB
None


In [ ]:
df.columns

Index(['sepal_l_cm', 'class'], dtype='object')

In [ ]:
df.count()

,0
sepal_l_cm,150
sepal_w_cm,150
petal_l_cm,150
petal_w_cm,150
class,150


Um método importante para visualização dos dados é a describe()

Exemplo:


In [ ]:
df = pd.read_csv(arquivo) #você só terá acesso ao arquivo se autorizar o Colab a acessar o seu Google drive rodando o comando da célular anterior
print(df.describe())

       sepal_l_cm  sepal_w_cm  petal_l_cm  petal_w_cm
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667
std      0.828066    0.433594    1.764420    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000


Para uma visualização mais detalhada dos nossos dados podemos utilizar uma biblioteca chamada de Pandas-Profiling
Essa biblioteca não vem por padrão instalada, nem localmente, nem no Colab.

Portanto, precisamos instalar através do comando:


In [ ]:
!pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

     - 17.9 MB 33.6 MB/s 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 18.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 62.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 39.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 8.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.9/65.9 kB 4.4 MB/s eta 0:00:00
  Created wheel for ydata-profiling: filename=ydata_profiling-0.0.dev0-py2.py3-none-any.whl size=400421 sha256=a448b22af12f4f662ec7f1e4aec1bb0071a4f3a41554b3794d25b3684be4a4ae
  Stored in directory: /tmp/pip-ephem-wheel-cache-2_bami4g/wheels/71/3c/c6/1dde962797c52d907d477fe1b35111dccb8c4574b0ad7a8cb7
Successfully built ydata-profiling


Em seguida podemos importar e executá-lo:

In [ ]:
import pandas_profiling
profile = pandas_profiling.ProfileReport(df)
profile

/tmp/ipython-input-1039414428.py:1: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  import pandas_profiling


Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]


100%|██████████| 5/5 [00:00<00:00, 1942.35it/s]


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

# Redundância, duplicação, conflito, transformação

In [ ]:
# Primeiro criamos um DataFrame com dados redundantes
df = pd.DataFrame({
    "Nome": ["João", "Maria", "José", "Silvio"],
    "Gênero": ["Masculino", "Feminino", "Masculino", "Masculino"],
    "UF": ["PE", "PE", "PB", "RN"]
  }
)
df.head()

,Nome,Gênero,UF
0,João,Masculino,PE
1,Maria,Feminino,PE
2,José,Masculino,PB
3,Silvio,Masculino,RN


In [ ]:
df.columns

Index(['Nome', 'Gênero', 'UF'], dtype='object')

In [ ]:
# Filtrando as linhas referentes a PE
df = df[df['UF'] == 'PE']
df.head()

,Nome,Gênero,UF
0,João,Masculino,PE
1,Maria,Feminino,PE


In [ ]:
# Usando o método 'drop'
df = df.drop(labels=['UF'], axis=1)

df.head()

,Nome,Gênero
0,João,Masculino
1,Maria,Feminino


## Linhas duplicadas

In [ ]:
# Criando um Dataframe com linhas duplicados
df = pd.DataFrame({'Nome': ['João', 'Maria', 'João', 'Silvio'], 'Gênero': ['Masculino', 'Feminino', 'Masculino', 'Masculino'], 'UF': ['PE', 'PE', 'PE', 'RN']})
df.head()

,Nome,Gênero,UF
0,João,Masculino,PE
1,Maria,Feminino,PE
2,João,Masculino,PE
3,Silvio,Masculino,RN


In [ ]:
df = df.drop_duplicates() #usamos o método drop_duplicates para remover as linhas duplicadas no DataFrame
df.head()

,Nome,Gênero,UF
0,João,Masculino,PE
1,Maria,Feminino,PE
3,Silvio,Masculino,RN


## Dados conflitantes

In [ ]:
# Criando um Dataframe com dados conflitantes
df = pd.DataFrame({'Paciente': ['João', 'Maria', 'José', 'Silvio'], 'Vacina': ['Coronavac', 'Butantan', 'Astrazeneca', 'Fiocruz']})
df.head()

,Paciente,Vacina
0,João,Coronavac
1,Maria,Butantan
2,José,Astrazeneca
3,Silvio,Fiocruz


In [ ]:
# Considerando que Coronovac é igual a Butantan e Astrazeneca é igual a Fiocruz
df.loc[df['Vacina'] == 'Butantan', 'Vacina'] = 'Coronavac'
df.loc[df['Vacina'] == 'Fiocruz', 'Vacina'] = 'Astrazeneca'
df.head()

,Paciente,Vacina
0,João,Coronavac
1,Maria,Coronavac
2,José,Astrazeneca
3,Silvio,Astrazeneca


## Codificação

In [ ]:
# Criando um Dataframe com dados para serem codificados
df = pd.DataFrame({'Veículo': ['Fiat', 'Ford', 'Fiat', 'Jeep'], 'Área': ['Capital', 'Interior', 'RMR', 'Capital'], 'Consumo': [10, 15, 8, 6], 'Suspeito': ['Sim', 'Sim', 'Não', 'Não']})
df.head()

,Veículo,Área,Consumo,Suspeito
0,Fiat,Capital,10,Sim
1,Ford,Interior,15,Sim
2,Fiat,RMR,8,Não
3,Jeep,Capital,6,Não


In [ ]:
df.loc[df['Veículo'] == 'Fiat', 'Veículo'] = 0
df.loc[df['Veículo'] == 'Ford', 'Veículo'] = 1
df.loc[df['Veículo'] == 'Jeep', 'Veículo'] = 2

df.loc[df['Área'] == 'Capital', 'Área'] = 0
df.loc[df['Área'] == 'Interior', 'Área'] = 1
df.loc[df['Área'] == 'RMR', 'Área'] = 2

df.loc[df['Suspeito'] == 'Sim', 'Suspeito'] = 1
df.loc[df['Suspeito'] == 'Não', 'Suspeito'] = 0

df.head()

,Veículo,Área,Consumo,Suspeito
0,0,0,10,1
1,1,1,15,1
2,0,2,8,0
3,2,0,6,0
